### PR TITLE
Fixed Err "Cannot read property 'destruct' of null"

### PR DESCRIPTION
**Pull request by mustafasheikh1**
Fixed Err "Cannot read property 'destruct' of null"

### CODE REVIEW

**Comment by MrStLouis** [comment]
any reason this can't be merged? This error is pretty annoying with SSR/HMR

**Comment by mustafasheikh1** [comment]
@MrStLouis was wondering the same, still waiting for them to merge, maybe they're slow or busy something !!

**Comment by vitorhsb** [comment]
Any news on this?

**Comment by luckylks** [comment]
> Any news on this?

I guess I will have to revert back to Suneditor until this branch is merged. I can't use the main branch.

**Comment by mustafasheikh1** [comment]
> Any news on this?

Sadly no

**Comment by datgwaters** [comment]
build new version?

**Comment by prabhaw** [comment]
> build new version?

still a problem with is while changing the page it says
 TypeError: Cannot read property 'destruct' of null

**Comment by mehmetkarakamis** [comment]
Needs to be merged.

**Review by MrStLouis — APPROVED** [review]

**Pull request merged**
